<a href="https://colab.research.google.com/github/jahnavitelsang/DATASCIENCE/blob/main/PROB_AND_STATISTICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROBABILITY AND STATISTICS**

In [3]:
from scipy.stats import norm
a = norm(50000,10000)
x = a.cdf(60000)
print(x)

0.8413447460685429

In [4]:
from scipy.stats import norm
nd = norm(90,10)
x1 = 1-nd.cdf(100)
x1

np.float64(0.15865525393145707)

In [7]:
from scipy.stats import norm
nd = norm(600,20)
x3 = nd.cdf(660) - nd.cdf(600)
x3

np.float64(0.4986501019683699)

In [9]:
from scipy.stats import norm
mu = 10
sigma = 20 / 60
probability = norm.cdf(11, mu, sigma) - norm.cdf(10, mu, sigma)
print("Probability =", probability)

Probability = 0.4986501019683699

# **HYPOTHESIS**

In [3]:
import pandas as pd
import numpy as np
from scipy.stats import norm

In [4]:
df = pd.read_csv('/content/Bulbs_Lifespan.csv')

In [5]:
df.head()

   Lifespan (Hours)
0           1004.84
1            973.09
2           1012.38
3           1056.15
4            968.29

In [6]:
df.shape

(40, 1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Lifespan (Hours)  40 non-null     float64
dtypes: float64(1)
memory usage: 452.0 bytes

In [8]:
df.describe()

       Lifespan (Hours)
count         40.000000
mean         969.068000
std           47.640061
min          882.020000
25%          933.290000
50%          968.290000
75%          996.477500
max         1072.610000

In [ ]:
#parametrs from the senerio#

In [9]:
pop_mean = 1000
pop_std = 50
alpha = 0.05

In [19]:
#firstly given is pop mean and pop sdt, need to take the alpha valuse as default. #

In [13]:
sample_data = df['Lifespan (Hours)']   #to determone the z statistic we need sample data and its mean and also the n value that is the length of sample data#
sample_mean = sample_data.mean()
n = len(sample_data)

In [24]:
z_statistic = (sample_mean - pop_mean)/(pop_std/np.sqrt(n))

In [44]:
s = norm(1000,50)
p_value_twotailed = 2*(1-norm.cdf(abs(z_statistic)))

In [36]:
sample_mean

np.float64(969.068)

In [37]:
z_statistic

np.float64(-3.9126229033731343)

In [45]:
np.round(p_value_twotailed,4)

np.float64(0.0001)

In [41]:
if p_value_twotailed > alpha:
  print("Accept the null hypothesis")
else:
  print("Reject the null hypothesis")

Reject the null hypothesis

In [46]:
df = pd.read_csv('/content/Lungcapdata.csv')

In [47]:
df.shape

(725, 7)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LungCap    725 non-null    float64
 1   Age        725 non-null    int64
 2   Height     725 non-null    float64
 3   Smoke      725 non-null    object
 4   Gender     725 non-null    object
 5   Caesarean  725 non-null    object
 6   AgeRange   725 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 39.8+ KB

In [49]:
df.describe()

          LungCap         Age      Height
count  725.000000  725.000000  725.000000
mean     7.863148   12.326897   64.836276
std      2.662008    4.004750    7.202144
min      0.507000    3.000000   45.300000
25%      6.150000    9.000000   59.900000
50%      8.000000   13.000000   65.400000
75%      9.800000   15.000000   70.300000
max     14.675000   19.000000   81.800000

In [50]:
df.head()

   LungCap  Age  Height Smoke  Gender Caesarean   AgeRange
0    6.475    6    62.1    no    male        no   Age 6-15
1   10.125   18    74.7   yes  female        no  Age 16-19
2    9.550   16    69.7    no  female       yes  Age 16-19
3   11.125   14    71.0    no    male        no   Age 6-15
4    4.800    5    56.9    no    male        no    Under 5

In [53]:
lungcap = df['LungCap']    # to get the sample mean , need sample dataset and also the n value#
n = len(lungcap)
n

725

In [56]:
sample_mean = lungcap.mean()
sample_std = lungcap.std()

In [ ]:
# 95% confidence

In [59]:
from scipy.stats import t
confidence = 0.95
t_crit = t.ppf((1+confidence)/2,df = n-1)

In [61]:
margin_of_error = t_crit * sample_std/np.sqrt(n)

In [62]:
ci_upper = sample_mean + margin_of_error
ci_lower = sample_mean - margin_of_error

In [68]:
print("lower bound is :" ,np.round(ci_lower,2))
print("upper bound is :" ,np.round(ci_upper,2))

lower bound is : 7.67
upper bound is : 8.06