<a href="https://colab.research.google.com/github/jahnavitelsang/DATASCIENCE/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/Pharma_Industry.csv')

In [4]:
df.shape

(500, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Drug Dosage (mg)                500 non-null    float64
 1   Systolic Blood Pressure (mmHg)  500 non-null    float64
 2   Heart Rate (BPM)                500 non-null    float64
 3   Liver Toxicity Index (U/L)      500 non-null    float64
 4   Blood Glucose Level (mg/dL)     500 non-null    float64
 5   Drug Response                   500 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 23.6 KB

In [6]:
df.describe()

,Drug Dosage (mg),Systolic Blood Pressure (mmHg),Heart Rate (BPM),Liver Toxicity Index (U/L),Blood Glucose Level (mg/dL),Drug Response
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.0000
mean,-0.037761,0.214957,0.062871,0.054398,-0.171863,0.5200
std,0.979891,1.247567,0.971978,0.986001,0.983765,0.5001
min,-3.019512,-3.773897,-2.940389,-3.401277,-3.110431,0.0000
25%,-0.642003,-0.565168,-0.648157,-0.586085,-0.797715,0.0000
50%,-0.019340,0.201532,0.027732,-0.065661,-0.108106,1.0000
75%,0.641151,0.951375,0.710774,0.633914,0.513555,1.0000
max,2.949094,4.111751,3.193108,3.373269,2.518023,1.0000

In [3]:
df.head()

,Drug Dosage (mg),Systolic Blood Pressure (mmHg),Heart Rate (BPM),Liver Toxicity Index (U/L),Blood Glucose Level (mg/dL),Drug Response
0,-0.128538,0.303280,-1.881849,0.258286,-0.792011,1
1,-1.846188,2.865142,-0.929511,2.866786,-0.719447,1
2,-1.252393,-1.541613,0.363632,-0.325370,0.191314,0
3,1.992515,-1.142779,-0.766657,0.975286,-0.823355,1
4,0.377100,0.538410,-0.029263,1.896015,-0.960130,1

In [17]:
X = df.iloc[:,0:3]
y = df['Drug Response']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [19]:
#Define svm with different kernels
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [20]:
#Using diff kernels
svm_linear = SVC(kernel='linear')
svm_poly = SVC(kernel='poly', degree = 3)
svm_rbf = SVC(kernel='rbf', gamma = 0.2)

In [21]:
#Now lets train the data set
svm_linear.fit(X_train, y_train)
y_pred = svm_linear.predict(X_test)
accuracy_linear = accuracy_score(y_test, y_pred)

In [22]:
#Train svm with poly kernel
svm_poly.fit(X_train, y_train)
y_pred = svm_poly.predict(X_test)
accuracy_poly = accuracy_score(y_test, y_pred)

In [23]:
svm_rbf.fit(X_train, y_train)
y_pred = svm_rbf.predict(X_test)
accuracy_rbf = accuracy_score(y_test, y_pred)

In [25]:
print("Accuracy with linear kernel:", accuracy_linear)
print("Accuracy with poly kernel:", accuracy_poly)
print("Accuracy with rbf kernel:", accuracy_rbf)

Accuracy with linear kernel: 0.5866666666666667
Accuracy with poly kernel: 0.58
Accuracy with rbf kernel: 0.6266666666666667

In [27]:
#Using PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_pca = pca.fit_transform(X)

In [39]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.3, random_state=42)

In [40]:
#Train using svm
svm_linear = SVC(kernel='linear')
svm_poly = SVC(kernel='poly', degree = 3)
svm_rbf = SVC(kernel='rbf', gamma = 0.2)

In [56]:
svm_linear.fit(X_pca, y)
y_pred_linear_pca = svm_linear.predict(X_pca)
accuracy_linear_pca = accuracy_score(y, y_pred_linear_pca)

In [59]:
svm_poly.fit(X_pca, y)
y_pred_poly_pca = svm_poly.predict(X_pca)
accuracy_poly_pca = accuracy_score(y, y_pred_poly_pca)

In [60]:
svm_rbf.fit(X_train_pca, y_train_pca)
y_pred_rbf_pca = svm_rbf.predict(X_pca)
accuracy_rbf_pca = accuracy_score(y, y_pred_rbf_pca)

In [61]:
print("Accuracy with linear kernel:", accuracy_linear_pca)
print("Accuracy with poly kernel:", accuracy_poly_pca)
print("Accuracy with rbf kernel:", accuracy_rbf_pca)

Accuracy with linear kernel: 0.604
Accuracy with poly kernel: 0.596
Accuracy with rbf kernel: 0.638